name: Build and Release Theme

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install and build
      - run: npm install
      - run: npm run build

      # Prepare release folder without copying itself
      - name: Prepare release files
        run: |
          mkdir -p release/advancedcare
          rsync -av --exclude=.git --exclude=.github --exclude=node_modules --exclude=release \
                    --exclude=advancedcare.zip --exclude=*.log --exclude=*.DS_Store \
                    ./ release/advancedcare

      # Extract version from style.css
      - name: Get theme version
        id: get_version
        run: |
          VERSION=$(grep -i 'Version:' release/advancedcare/style.css | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Zip only the contents of the theme folder, not the folder itself
      - name: Zip theme contents
        run: |
          cd release/advancedcare
          zip -r ../../advancedcare.zip ./*

      # Create GitHub release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: advancedcare.zip
