name: Build and Release Theme

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build theme
        run: npm run build

      - name: Get theme version from style.css
        id: get_version
        run: |
          VERSION=$(grep -i 'Version:' style.css | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Package theme and create release zip
        run: |
          # 🔥 Clean up previous build artifacts
          rm -rf final advancedcare.zip

          # ✅ Create target folder
          mkdir -p final/advancedcare

          # ✅ Copy everything (excluding problematic stuff) into the zip folder
          rsync -av --exclude=".git*" --exclude=".github" --exclude="node_modules" \
            --exclude="*.zip" --exclude="*.log" --exclude="*.DS_Store" --exclude="__MACOSX" \
            --exclude="final" \
            ./ final/advancedcare

          # ✅ Force overwrite style.css to make sure it's there
          cp style.css final/advancedcare/style.css

          # ✅ Normalize permissions
          cd final
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;

          # ✅ Create the final zip
          zip -r ../advancedcare.zip advancedcare

      - name: Verify zip integrity
        run: unzip -t advancedcare.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: advancedcare.zip
