name: Build and Release Theme

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install and build
      - run: npm install
      - run: npm run build

      # Clean and move files into a release-ready folder
      - name: Prepare advancedcare folder for release
        run: |
          mkdir -p advancedcare
          shopt -s dotglob
          mv * advancedcare

      # Extract version from style.css
      - name: Get theme version
        id: get_version
        run: |
          VERSION=$(grep -i 'Version:' advancedcare/style.css | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Create ZIP that contains the top-level advancedcare folder
      - run: zip -r advancedcare.zip advancedcare

      # Create GitHub release with correct version tag
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: advancedcare.zip
