name: Build and Release Theme

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install and build
      - run: npm install
      - run: npm run build

      # Prepare release folder without nesting theme folder
      - name: Prepare release files
        run: |
          mkdir -p release
          rsync -av --delete \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='release' \
            --exclude='*.zip' \
            --exclude='*.log' \
            --exclude='*.DS_Store' \
            --exclude='__MACOSX' \
            ./ release/

      # Normalize permissions for WordPress compatibility
      - name: Normalize permissions
        run: |
          cd release
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;

      # Extract theme version from style.css
      - name: Get theme version
        id: get_version
        run: |
          VERSION=$(grep -i 'Version:' release/style.css | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Zip ONLY the theme contents (no parent folder)
      - name: Create theme zip
        run: |
          cd release
          zip -r ../advancedcare.zip . -x "*.DS_Store" -x "__MACOSX/*"

      # Optional: Verify zip
      - name: Verify zip integrity
        run: unzip -t advancedcare.zip

      # Upload release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: advancedcare.zip
