name: Build and Release Theme

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # ✅ Grab version from style.css
      - name: Get theme version
        id: get_version
        run: |
          VERSION=$(grep -i 'Version:' style.css | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # ✅ Create zip of theme root (NO parent folder!)
      - name: Create theme zip
        run: |
          zip -r advancedcare.zip . -x "*.git*" -x "*.github*" -x "node_modules/*" -x "release/*" -x "*.zip" -x "*.log" -x "*.DS_Store" -x "__MACOSX/*"

      - name: Verify zip integrity
        run: unzip -t advancedcare.zip

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: advancedcare.zip
