name: Build and Release Theme

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm run build

      # ✅ Create proper advancedcare/ folder with only clean theme files
      - name: Prepare theme folder
        run: |
          mkdir -p temp/advancedcare
          rsync -av --exclude=.git --exclude=.github --exclude=node_modules --exclude=temp ./ temp/advancedcare

      # ✅ Zip with top-level folder 'advancedcare'
      - name: Zip theme
        run: |
          cd temp
          zip -r ../advancedcare.zip advancedcare

      - name: Get version from style.css
        id: get_version
        run: |
          VERSION=$(grep -i 'Version:' temp/advancedcare/style.css | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: advancedcare.zip
